### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [tnpalafox/ProyectoFinalBioinf2017-II#1]
OK, pero no olvides especificar con qué software harás el ensamblado o cómo será diferente a lo ya existente.

No olvides poner en cursiva el nombre de las especies en tus markdown.

**Comment by tnpalafox** [comment]
@AliciaMstt  Hola.
Para mi proyecto de doctorado trabajaré con secuencias obtenidas mediante ddRAD, desde el inicio tenía planteado usar Stacks (quisiera aprender a utilizarlo), sin embargo en tu paper utilizas este software (el cual ya no podré utilizar yo), sin embargo quería pedirte un consejo:
Teniendo en cuenta que utilizaré ddRAD, ¿que otro software me recomiendas usar-aprender?, por desgracia aún no tengo los datos de mi proyecto, pero si considero que debería utilizar (en el trabajo final) un software que me sea útil cuando cuente por fin con mis datos.

Saludos y muchas gracias.

**Comment by AliciaMstt** [comment]
Está bien si utilizas Stacks, pero asegúrate de que sea la versión más reciente y has algo diferente a lo que yo hice. Por ejemplo puedes incluir for loops en tus scripts de ensamblado o probar otros parámetros a los que yo probé. Si tu proyecto con tus datos es más filogenético que de gen pop, tmb podrías ensamblar los datos de Berberis utilizando pyRAD.

**Comment by AzaleaGuerra** [comment]
Hay varias pipelines para ensamblar de novo y cuál elijas depende en parte de tu pregunta biológica, si es filogenética, como Alicia te comenta, pyRAD es una buena opción. Stacks, aunque es muy usado, tiene algunas problemas. Te dejo el link a un artículo donde comparan algunas pipelines: http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0161333

**Comment by tnpalafox** [comment]
@AliciaMstt  y @AzaleaGuerra ya modifiqué el formato de mi md para que se vean las cursivas, también leí el artículo que Azalea me envió (ahora tengo más dudas de que software usar), no me quiero casar desde ahorita con alguno, posiblemente use los dos para hacer comparaciones entre ellos.

**Comment by AliciaMstt** [comment]
Puedes intentar correr ambos con un set pequeño de datos y así no creo que tengas problemas con la memoria y el tiempo. Tómalo como datos de chocolate para aprender a correr ambas pipelines.
